%% duallayer2_gerd_03_iCanClean.m
%
% Description:
%   This script applies the iCanClean algorithm to phantom head EEG datasets 
%   in order to remove noise contributions from dedicated noise reference channels. 
%   Each dataset is processed in two versions: (1) with iCanClean, and (2) without 
%   iCanClean (traditional preprocessing). Both versions are saved for later comparison. 
%   Information about the iCanClean decomposition is stored in the MEASUREMENTS structure.
%
% Workflow:
%   - Define input/output paths and load parameters
%   - Loop across measurement sessions and noise conditions
%   - For each dataset:
%       * Load preprocessed EEG file
%       * Apply iCanClean to EEG vs. noise reference channels
%       * Save both iCanClean and traditional (no iCC) versions
%       * Store iCanClean info in MEASUREMENTS
%
% Inputs:
%   - Preprocessed EEG datasets (.set) from CHECKPATH
%   - 'params.mat' containing iCanClean parameters
%   - 'MEAS.mat' structure with metadata (extended by each script)
%
% Outputs:
%   - EEG datasets (.set) with and without iCanClean, stored in ICCPATH
%   - Updated MEASUREMENTS.mat with iCanClean info per dataset
%
% Dependencies:
%   - EEGLAB (for EEG data handling and saving)
%   - iCanClean toolbox/function
%   - params.mat (generated by duallayer2_gerd_00_configfiles.m)
%
% Author: Melanie, 2025

%% Preparations

close all; clear all; clc;                                                                          % start with fresh workspace

% set paths

MAINPATH = 'Q:\Neuro\data\projects\all_gait\dual-layerCap\dual-layer-2024_25\eegl\';               % adjust this path to your local environment!!!
PATHIN = [MAINPATH, 'rawdata\gerd\'];                                                                % path to raw data (changed from task-Flanker!!!)
PATHOUT = [MAINPATH, 'derivatives\gerd\'];                                                           % path for data derivatives created on the way

CHECKPATH = [PATHOUT, 'duallayer2_gerd_01_first-Check\'];
ICCPATH = [PATHOUT, 'duallayer2_gerd_02_iCC\'];                                                      % path for ICC data 

if ~isfolder(ICCPATH)                                                                                % if the path doesn't exist yet, create it
    mkdir(ICCPATH)
end


cd(MAINPATH)
load('params.mat');                                                                                 % load params (written in duallayer2_gerd_00_configfiles.m)
load('MEAS.mat');                                                                                   % load info struct, which is extended with each script

%% start

for meas = 1:length(MEASUREMENTS)

    [ALLEEG EEG CURRENTSET ALLCOM] = eeglab;                                                        % start EEGLAB

    SUBCHECKPATH = [CHECKPATH, MEASUREMENTS(meas).ID, '\'];
    cd(SUBCHECKPATH)                                                                                % set filepath
    file = dir(fullfile(SUBCHECKPATH, '*.set'));                                                   % get access to data sets

    MEASICCPATH = [ICCPATH, MEASUREMENTS(meas).ID, '\'];                        % create path for measurement        
    if ~isfolder(MEASICCPATH)
        mkdir(MEASICCPATH)
    end

    file_name = file.name;                                                         % get current file name
    EEG = pop_loadset('filename',file_name,'filepath',SUBCHECKPATH);

    [EEG.chanlocs(find(contains({EEG.chanlocs.labels}, 'R'))).type] = deal('Noise');                % assign the Noise label to the Noise electrodes
    [EEG.chanlocs(find(~contains({EEG.chanlocs.labels}, 'R'))).type] = deal('EEG');                % assign the Noise label to the Noise electrodes

    % acutal iCanClean -----------------------------------------------------------------------
    
    do_iCC = [false,true];
    
    for idx = 1:length(do_iCC)
        
        if do_iCC(idx)                                                                          % iCanClean

            EEG_chans = find(strcmpi('EEG',{EEG.chanlocs.type}));                               % get EEG channel indices
            Noise_chans = find(strcmpi('Noise',{EEG.chanlocs.type}));                           % get Noise channel indices          

            EEG = iCanClean(EEG, EEG_chans, Noise_chans, 0, params);                            % perform iCanClean

            cd(MEASICCPATH);
            EEG.setname = [MEASUREMENTS(meas).ID, '_', 'ICC'];
            EEG = pop_saveset(EEG, 'filename', [EEG.setname, '_preproc-iCC_eeg'], 'filepath', MEASICCPATH);  % save data set
            
            MEASUREMENTS(meas).ICC_info = EEG.etc.iCanClean;        % save iCC info
            
        else                                                                                    % no iCanClean

            cd(MEASICCPATH);
            EEG.setname = [MEASUREMENTS(meas).ID, '_', 'trad'];
            EEG = pop_saveset(EEG, 'filename', [EEG.setname, '_preproc-trad_eeg'], 'filepath', MEASICCPATH); % save data set    
            
        end                                                                                     % end if-else deciding about preproc option
    end                                                                                         % end loop across preproc options

end                                                                                                 % end loop acrss measurements


save([MAINPATH,'MEAS'],'MEASUREMENTS');                                                             % save information

%% extract removed components

for idx = 1:9

    rem_comps_PH(idx) = MEASUREMENTS(idx).ICC_info.numNoiseCompsRemovedOnAvg;

end

avg = mean(rem_comps_PH);
my_min = min(rem_comps_PH);
my_max = max(rem_comps_PH);

%% end


close all; clear all; clc;                                                                          % start with fresh workspace

% set paths --------------------------------------------------------------------------------------

MAINPATH = 'Q:\Neuro\data\projects\all_gait\dual-layerCap\dual-layer-2024_25\eegl\';               % adjust this path to your local environment!!!
PATHOUT = [MAINPATH, 'derivatives\gerd\'];                                                           % path for data derivatives created on the way

CHECKPATH = [PATHOUT, 'duallayer2_gerd_01_first-Check2\'];
ICCPATH = [PATHOUT, 'duallayer2_gerd_02_iCC\'];                                                      % path for iCanClean data 
ICAPATH = [PATHOUT, 'duallayer2_gerd_03_iCA\'];                                                      % path for ICA data 

if ~isfolder(ICAPATH)                                                                                % if the path doesn't exist yet, create it
    mkdir(ICAPATH)
end

% parameters -------------------------------------------------------------------------------------

cd(MAINPATH)
load('MEAS.mat');
load('df_params.mat')


%% Start Processing


for meas = 1:length(MEASUREMENTS)

    SUBICCPATH = [ICCPATH, MEASUREMENTS(meas).ID, '\'];
    cd(SUBICCPATH)                                                                                  % set filepath
    files = dir(fullfile(SUBICCPATH, '*.set'));                                                     % get access to data sets

    for file = 1:length(files)

        [ALLEEG EEG CURRENTSET ALLCOM] = eeglab;                                                    % start EEGLAB

        file_name = files(file).name;                                                               % get current file name
        EEG = pop_loadset('filename',file_name,'filepath',SUBICCPATH);

        if contains(file_name, 'trad')                                                              % sort of iCC conditions
            cond = 'trad';
        else
            cond = 'ICC';
        end


        % continue with real preparation for ICA -------------------------------------------------
   
        go_chans = EEG.chanlocs(strcmp({EEG.chanlocs.type},'EEG'));                                 % get EEG channels
        go_labels = {go_chans.labels};                                                              % get their labels
        
        EEG = pop_select( EEG, 'channel',go_labels);                                                % only keep EEG chans for ICA
        [ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'gui','off'); 

        MEASUREMENTS(meas).nchans_ICA = EEG.nbchan;                                                 % update number of channels
    
        EEG = pop_runica(EEG, 'icatype', 'runica', 'extended',1,'interrupt','on');                  % run ICA
        EEG.setname = [MEASUREMENTS(meas).ID, '_preproc-ICAWeights'];                               % give set name
        [ALLEEG EEG CURRENTSET] = eeg_store(ALLEEG, EEG);                                           % save as new set
    
        % try out dipole fitting -----------------------------------------------------------------

        EEG = pop_dipfit_settings( EEG, 'hdmfile', [MAINPATH,'standard_vol.mat'], ...               % dipole fitting settings (for trying out stuff)
            'mrifile',[MAINPATH, 'standard_mri.mat'], 'chanfile',[MAINPATH, 'standard_1020.elc'],...
            'coordformat','MNI');
        
        [ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
        EEG = pop_dipfit_gridsearch(EEG, [1:length(EEG.chanlocs)] , df.gridA, df.gridB, df.gridC, 0.4);               % dipole fitting (for trying out stuff)
      
        SUBICAPATH = [ICAPATH,MEASUREMENTS(meas).ID,'\'];
        if ~isfolder(SUBICAPATH)                                                                    % if the path doesn't exist yet, create it
            mkdir(SUBICAPATH)
        end
    
        EEG.setname = [MEASUREMENTS(meas).ID, '_preproc-', cond, '_ICAWeights'];
        EEG = pop_saveset(EEG, 'filename', EEG.setname, 'filepath', SUBICAPATH);                    % save data set
    end                                                                                             % end loop across preproc conditions
end                                                                                                 % end loop across measurements


save([MAINPATH,'MEAS'],'MEASUREMENTS');  

%%

close all; clear all; clc;                                                                          % start with fresh workspace

% set paths

MAINPATH = 'Q:\Neuro\data\projects\all_gait\dual-layerCap\dual-layer-2024_25\eegl\';
cd(MAINPATH)

PATHOUT = [MAINPATH, 'derivatives\gerd\'];                                                          % path for data derivatives created on the way

ICAPATH = [PATHOUT, 'duallayer2_gerd_03_iCA\'];                                                     % path for ICA data 
EPOPATH = [PATHOUT, 'duallayer2_gerd_04_epo\'];                                                     % path for epoch data 

if ~isfolder(EPOPATH)                                                                                % if the path doesn't exist yet, create it
    mkdir(EPOPATH)
end


% load parameters

load('erp.mat');  
load('MEAS.mat');  


%% start

for meas = 1:length(MEASUREMENTS)

    [ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;                                                     % start EEGLAB

    SUBICAPATH = [ICAPATH, MEASUREMENTS(meas).ID, '\'];

    cd(SUBICAPATH)                                                                                  % set filepath
    files = dir(fullfile(SUBICAPATH, '*.set'));                                                     % get access to data sets

    for file = 1:length(files)

        file_name = files(file).name;
        EEG = pop_loadset('filename',file_name,'filepath',SUBICAPATH);
        [ALLEEG EEG CURRENTSET] = eeg_store(ALLEEG, EEG);                                           % save as new set (ALLEEG)

        if contains(file_name, 'trad')                                                              % sort iCC condition
            cond = 'trad';
        else
            cond = 'ICC';
        end


        SUBEPOSME = [EPOPATH, MEASUREMENTS(meas).ID, '\'];
        if ~isfolder(SUBEPOSME)                                                                     % if the path doesn't exist yet, create it
            mkdir(SUBEPOSME)
        end

        EEG = pop_interp(EEG, EEG.urchanlocs , 'spherical');                                        % and interpolate them using urchanlocs        

    
        refchans = strmatch('TP', {EEG.chanlocs.labels});                                           % find mastoid electrodes
        EEG = pop_reref(EEG, refchans);                                                             % re-reference data to TP9 and TP10
        EEG = pop_epoch( EEG, {erp.gerd_events{meas}}, [erp.FROM erp.TO], 'epochinfo', 'yes');      % cut SME-epochs from -.2 to 0.8 s
        EEG = pop_rmbase( EEG, [erp.FROM*1000 0] ,[]);                                              % baseline correction  

        nchan = EEG.nbchan;
    
        EEG = pop_jointprob(EEG,1,[1:nchan] ,erp.REJ,erp.REJ,0,1,0,[],0);                           % artefact correction using joint probabilities
        EEG = pop_rejkurt(EEG,1,[1:nchan] ,erp.REJ,erp.REJ,0,1,0,[],0);                             % artefact correction using channel kurtosis
        EEG.setname = [num2str(file), '_',MEASUREMENTS(meas).ID, '_', cond, '_epochs']; % new set name
        [ALLEEG EEG CURRENTSET] = eeg_store(ALLEEG, EEG);                                           % save as new set (ALLEEG)

        EEG = pop_saveset(EEG, 'filename', EEG.setname, 'filepath', SUBEPOSME);    % save data set
    
    end


end

