%% duallayer2_gerd_03_iCanClean.m
%
% Description:
%   This script applies the iCanClean algorithm to phantom head EEG datasets 
%   in order to remove noise contributions from dedicated noise reference channels. 
%   Each dataset is processed in two versions: (1) with iCanClean, and (2) without 
%   iCanClean (traditional preprocessing). Both versions are saved for later comparison. 
%   Information about the iCanClean decomposition is stored in the MEASUREMENTS structure.
%
% Workflow:
%   - Define input/output paths and load parameters
%   - Loop across measurement sessions and noise conditions
%   - For each dataset:
%       * Load preprocessed EEG file
%       * Apply iCanClean to EEG vs. noise reference channels
%       * Save both iCanClean and traditional (no iCC) versions
%       * Store iCanClean info in MEASUREMENTS
%
% Inputs:
%   - Preprocessed EEG datasets (.set) from CHECKPATH
%   - 'params.mat' containing iCanClean parameters
%   - 'MEAS.mat' structure with metadata (extended by each script)
%
% Outputs:
%   - EEG datasets (.set) with and without iCanClean, stored in ICCPATH
%   - Updated MEASUREMENTS.mat with iCanClean info per dataset
%
% Dependencies:
%   - EEGLAB (for EEG data handling and saving)
%   - iCanClean toolbox/function
%   - params.mat (generated by duallayer2_gerd_00_configfiles.m)
%
% Author: Melanie, 2025

%% Preparations

close all; clear all; clc;                                                                          % start with fresh workspace

% set paths

MAINPATH = 'R:\Ferris-Lab\mklapprott\eegl\';                                                        % adjust this path to your local environment!!!
PATHIN = [MAINPATH, 'rawdata\gerd\'];                                                                % path to raw data (changed from task-Flanker!!!)
PATHOUT = [MAINPATH, 'derivatives\gerd\'];                                                           % path for data derivatives created on the way

CHECKPATH = [PATHOUT, 'duallayer2_gerd_01_first-Check\'];
ICCPATH = [PATHOUT, 'duallayer2_gerd_02_iCC\'];                                                      % path for ICC data 

if ~isfolder(ICCPATH)                                                                                % if the path doesn't exist yet, create it
    mkdir(ICCPATH)
end


cd(MAINPATH)
load('params.mat');                                                                                 % load params (written in duallayer2_gerd_00_configfiles.m)
load('MEAS.mat');                                                                                   % load info struct, which is extended with each script

%% start

for meas = 1:length(MEASUREMENTS)

    [ALLEEG EEG CURRENTSET ALLCOM] = eeglab;                                                        % start EEGLAB

    SUBCHECKPATH = [CHECKPATH, MEASUREMENTS(meas).ID, '\'];
    cd(SUBCHECKPATH)                                                                                % set filepath
    file = dir(fullfile(SUBCHECKPATH, '*.set'));                                                   % get access to data sets

    MEASICCPATH = [ICCPATH, MEASUREMENTS(meas).ID, '\'];                        % create path for measurement        
    if ~isfolder(MEASICCPATH)
        mkdir(MEASICCPATH)
    end

    file_name = file.name;                                                         % get current file name
    EEG = pop_loadset('filename',file_name,'filepath',SUBCHECKPATH);

    % acutal iCanClean -----------------------------------------------------------------------
    
    do_iCC = [false,true];
    
    for idx = 1:length(do_iCC)
        
        if do_iCC(idx)                                                                          % iCanClean

            EEG_chans = find(strcmpi('EEG',{EEG.chanlocs.type}));                               % get EEG channel indices
            Noise_chans = find(strcmpi('Noise',{EEG.chanlocs.type}));                           % get Noise channel indices          
            
            EEG = iCanClean(EEG, EEG_chans, Noise_chans, 0, params);                            % perform iCanClean

            cd(MEASICCPATH);
            EEG.setname = [MEASUREMENTS(meas).ID, '_', 'ICC'];
            EEG = pop_saveset(EEG, 'filename', [EEG.setname, '_preproc-iCC_eeg'], 'filepath', MEASICCPATH);  % save data set
            
            MEASUREMENTS(meas).ICC_info = EEG.etc.iCanClean;        % save iCC info
            
        else                                                                                    % no iCanClean

            cd(MEASICCPATH);
            EEG.setname = [MEASUREMENTS(meas).ID, '_', 'trad'];
            EEG = pop_saveset(EEG, 'filename', [EEG.setname, '_preproc-trad_eeg'], 'filepath', MEASICCPATH); % save data set    
            
        end                                                                                     % end if-else deciding about preproc option
    end                                                                                         % end loop across preproc options

end                                                                                                 % end loop acrss measurements


save([MAINPATH,'MEAS'],'MEASUREMENTS');                                                             % save information

%% end


